"""Full OAK reference data: universities and journals by specialty.

Sourced from the official OAK lists (124+ state OTMs, 70 non-state/international
OTMs, and OAK-approved journals grouped by 24 specialty directions). Seeding in
app.py is additive and de-duplicates against existing rows by a normalized key,
so importing this never creates apostrophe-variant duplicates.
"""

# ── Universities ────────────────────────────────────────────────────────────
# (name, type)  type ∈ {'davlat', 'xususiy', 'xalqaro'}
UNIVERSITY_SEED = [
    # ── 1-QISM: Davlat OTMlari ──
    ('Abu Ali Ibn Sino Nomidagi Buxoro Davlat Tibbiyot Instituti', 'davlat'),
    ('Abu Rayhon Beruniy nomidagi Urganch davlat universiteti', 'davlat'),
    ('Ajiniyoz nomidagi Nukus davlat pedagogika instituti', 'davlat'),
    ('Andijon davlat chet tillari instituti', 'davlat'),
    ('Andijon davlat pedagogika instituti', 'davlat'),
    ('Andijon davlat texnika instituti', 'davlat'),
    ('Andijon davlat tibbiyot instituti', 'davlat'),
    ('Andijon davlat universiteti', 'davlat'),
    ('Andijon mashinasozlik instituti', 'davlat'),
    ("Andijon qishloq xo'jaligi va agrotexnologiyalar instituti", 'davlat'),
    ('Berdaq nomidagi Qoraqalpoq davlat universiteti', 'davlat'),
    ("Botir Zokirov nomidagi Milliy estrada san'ati instituti", 'davlat'),
    ('Buxoro davlat pedagogika instituti', 'davlat'),
    ('Buxoro davlat texnika universiteti', 'davlat'),
    ('Buxoro davlat universiteti', 'davlat'),
    ('Buxoro muhandislik-texnologiya instituti', 'davlat'),
    ('Chirchiq davlat pedagogika universiteti', 'davlat'),
    ('"Cyber university" davlat universiteti', 'davlat'),
    ("Farg'ona davlat texnika universiteti", 'davlat'),
    ('Farg\'ona davlat universiteti', 'davlat'),
    ("Farg'ona jamoat salomatligi tibbiyot instituti", 'davlat'),
    ("Farg'ona politexnika instituti", 'davlat'),
    ('Geologiya fanlari universiteti', 'davlat'),
    ('Guliston davlat pedagogika instituti', 'davlat'),
    ('Guliston davlat universiteti', 'davlat'),
    ('Ipak yo\'li turizm va madaniy meros xalqaro universiteti', 'davlat'),
    ('Jahon iqtisodiyoti va diplomatiya universiteti', 'davlat'),
    ('Jamoat xavfsizligi universiteti', 'davlat'),
    ('Jizzax davlat pedagogika universiteti', 'davlat'),
    ('Jizzax politexnika instituti', 'davlat'),
    ('Kamoliddin Behzod nomidagi Milliy rassomlik va dizayn instituti', 'davlat'),
    ("Kattaqo'rg'on davlat pedagogika instituti", 'davlat'),
    ("Mirzo Ulug'bek nomidagi O'zbekiston Milliy universiteti", 'davlat'),
    ("Mirzo Ulug'bek nomidagi O'zbekiston Milliy universitetining Jizzax filiali", 'davlat'),
    ("Mirzo Ulug'bek nomidagi Samarqand davlat arxitektura-qurilish universiteti", 'davlat'),
    ('Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti', 'davlat'),
    ('Muhammad al-Xorazmiy nomidagi TATU Nurafshon filiali', 'davlat'),
    ('Muhammad al-Xorazmiy nomidagi TATU Nukus filiali', 'davlat'),
    ('Muhammad al-Xorazmiy nomidagi TATU Qarshi filiali', 'davlat'),
    ('Namangan davlat chet tillari instituti', 'davlat'),
    ('Namangan davlat pedagogika instituti', 'davlat'),
    ('Namangan davlat texnika universiteti', 'davlat'),
    ('Namangan davlat universiteti', 'davlat'),
    ('Namangan muhandislik-qurilish instituti', 'davlat'),
    ('Namangan muhandislik-texnologiya instituti', 'davlat'),
    ("Namangan to'qimachilik sanoati instituti", 'davlat'),
    ('NDKTU huzuridagi Nukus konchilik instituti', 'davlat'),
    ('Navoiy davlat konchilik va texnologiyalar universiteti', 'davlat'),
    ('Navoiy davlat universiteti', 'davlat'),
    ("Nukus davlat pedagogika instituti Ellikqal'a fakulteti", 'davlat'),
    ('Nukus davlat texnika universiteti', 'davlat'),
    ('Oliy sport mahorati instituti', 'davlat'),
    ('Olmaliq davlat texnika instituti', 'davlat'),
    ("O'zbekiston davlat jismoniy tarbiya va sport universiteti Farg'ona filiali", 'davlat'),
    ("O'zbekiston davlat jismoniy tarbiya va sport universiteti Nukus filiali", 'davlat'),
    ("O'zbekiston davlat konservatoriyasi", 'davlat'),
    ("O'zbekiston Respublikasi Huquqni muhofaza qilish akademiyasi", 'davlat'),
    ("O'zbekiston davlat jahon tillari universiteti", 'davlat'),
    ("O'zbekiston davlat jismoniy tarbiya va sport universiteti", 'davlat'),
    ("O'zbekiston davlat konservatoriyasi Nukus filiali", 'davlat'),
    ("O'zbekiston davlat san'at va madaniyat instituti", 'davlat'),
    ("O'zbekiston davlat san'at va madaniyat instituti Nukus filiali", 'davlat'),
    ("O'zbekiston davlat san'at va madaniyat institutining Farg'ona filiali", 'davlat'),
    ("O'zbekiston davlat xoreografiya akademiyasi", 'davlat'),
    ("O'zbekiston davlat xoreografiya akademiyasi Urganch filiali", 'davlat'),
    ("O'zbekiston jurnalistika va ommaviy kommunikatsiyalar universiteti", 'davlat'),
    ("O'zbekiston milliy pedagogika universiteti", 'davlat'),
    ("O'zbekiston xalqaro islomshunoslik akademiyasi", 'davlat'),
    ('Oziq-ovqat texnologiyasi va muhandisligi xalqaro instituti', 'davlat'),
    ('Qarshi muhandislik-iqtisodiyot instituti', 'davlat'),
    ('Qarshi davlat texnika universiteti', 'davlat'),
    ('Qarshi davlat texnika universiteti Shaxrisabz oziq-ovqat fakulteti', 'davlat'),
    ('Qarshi davlat universiteti', 'davlat'),
    ("Qo'qon davlat universiteti", 'davlat'),
    ("Qoraqalpog'iston qishloq xo'jaligi va agrotexnologiyalar instituti", 'davlat'),
    ("Qoraqalpog'iston tibbiyot instituti", 'davlat'),
    ('Qoraqalpoq davlat universiteti Chimboy fakulteti', 'davlat'),
    ('SamDVMChBU Nukus filiali', 'davlat'),
    ('Samarqand agroinnovatsiyalar va tadqiqotlar instituti', 'davlat'),
    ('Samarqand davlat chet tillar instituti', 'davlat'),
    ('SamDChTI Narpay "Xorijiy tillar" fakulteti', 'davlat'),
    ('SamDChTI Payariq "Xorijiy tillar" fakulteti', 'davlat'),
    ('Samarqand davlat pedagogika instituti', 'davlat'),
    ('Samarqand davlat tibbiyot universiteti', 'davlat'),
    ('SamDU Agrobiotexnologiyalar va oziq-ovqat xavfsizligi instituti', 'davlat'),
    ('SamDU Denov tadbirkorlik va pedagogika instituti', 'davlat'),
    ('Samarqand davlat veterinariya meditsinasi, chorvachilik universiteti', 'davlat'),
    ('SamDVMChBU Toshkent filiali', 'davlat'),
    ('Samarqand iqtisodiyot va servis instituti', 'davlat'),
    ('Shahrisabz davlat pedagogika instituti', 'davlat'),
    ('Sharof Rashidov nomidagi Samarqand davlat universiteti', 'davlat'),
    ('"TIQXMMI" MTU Buxoro tabiiy resurslarni boshqarish instituti', 'davlat'),
    ('"TIQXMMI" MTU Qarshi irrigatsiya va agrotexnologiyalar instituti', 'davlat'),
    ('Toshkent davlat yuridik universiteti', 'davlat'),
    ('Termiz agrotexnologiyalar va innovatsion rivojlanish instituti', 'davlat'),
    ('Termiz davlat muhandislik va agrotexnologiyalar universiteti', 'davlat'),
    ('Termiz davlat pedagogika instituti', 'davlat'),
    ('Termiz davlat universiteti', 'davlat'),
    ('Termiz muhandislik-texnologiya instituti', 'davlat'),
    ('Toshkent farmatsevtika instituti', 'davlat'),
    ('Toshkent arxitektura-qurilish universiteti', 'davlat'),
    ('Toshkent axborot texnologiyalari universiteti Samarqand filiali', 'davlat'),
    ('Toshkent axborot texnologiyalari universiteti Urganch filiali', 'davlat'),
    ('Toshkent axborot texnologiyalari universiteti Zarafshon fakulteti', 'davlat'),
    ('Toshkent davlat agrar universiteti', 'davlat'),
    ('Toshkent davlat iqtisodiyot universiteti', 'davlat'),
    ('Toshkent davlat iqtisodiyot universiteti Andijon fakulteti', 'davlat'),
    ('Toshkent davlat iqtisodiyot universiteti Samarqand filiali', 'davlat'),
    ("Toshkent davlat iqtisodiyot universiteti To'rtko'l fakulteti", 'davlat'),
    ("Toshkent davlat o'zbek tili va adabiyoti universiteti", 'davlat'),
    ('Toshkent davlat sharqshunoslik universiteti', 'davlat'),
    ('Toshkent davlat stomatologiya instituti', 'davlat'),
    ('Toshkent davlat texnika universiteti', 'davlat'),
    ('Toshkent davlat tibbiyot universiteti', 'davlat'),
    ('Toshkent davlat tibbiyot universiteti Chirchiq filiali', 'davlat'),
    ('Toshkent davlat tibbiyot universiteti Termiz filiali', 'davlat'),
    ('Toshkent davlat transport universiteti', 'davlat'),
    ('Toshkent davlat yuridik universiteti Ixtisoslashtirilgan filiali', 'davlat'),
    ('"TIQXMMI" Milliy tadqiqot universiteti', 'davlat'),
    ('Toshkent kimyo-texnologiya instituti', 'davlat'),
    ('Toshkent kimyo-texnologiya instituti Shahrisabz filiali', 'davlat'),
    ('Toshkent kimyo-texnologiya instituti Yangiyer filiali', 'davlat'),
    ('Toshkent pediatriya tibbiyot instituti', 'davlat'),
    ('Toshkent tibbiyot akademiyasi Urganch filiali', 'davlat'),
    ("Toshkent to'qimachilik va yengil sanoat instituti", 'davlat'),
    ('Urganch davlat pedagogika instituti', 'davlat'),
    ("Yunus Rajabiy nomidagi O'zbek milliy musiqa san'ati instituti", 'davlat'),
    ('Andijon iqtisodiyot va qurilish instituti', 'davlat'),

    # ── 2-QISM: Nodavlat / xususiy / xalqaro OTMlar ──
    ('Akfa universiteti (Central Asian University)', 'xususiy'),
    ('Alfraganus University', 'xususiy'),
    ('Binary International University', 'xususiy'),
    ('British Management University', 'xalqaro'),
    ('Buxoro innovatsion tibbiyot instituti', 'xususiy'),
    ('Buxoro innovatsiyalar universiteti', 'xususiy'),
    ('Buxoro psixologiya va xorijiy tillar instituti', 'xususiy'),
    ('Cambridge International University', 'xalqaro'),
    ('Capital School - Innovatsion va ijtimoiy-iqtisodiyot universiteti', 'xususiy'),
    ('Central Asian Medical University', 'xususiy'),
    ('Colligium Humanum Varshava menejment universiteti', 'xalqaro'),
    ('Digital University', 'xususiy'),
    ('Diplomat University', 'xususiy'),
    ('Effect EDU', 'xususiy'),
    ('European Medical University', 'xalqaro'),
    ("Farg'ona shahridagi Koreya xalqaro universiteti", 'xalqaro'),
    ("Farmatsevtika ta'lim va tadqiqot instituti", 'xususiy'),
    ('Impuls tibbiyot instituti', 'xususiy'),
    ('International School of Finance and Technology (ISFT)', 'xalqaro'),
    ('Iqtisodiyot va pedagogika universiteti', 'xususiy'),
    ('IT-Park University', 'xususiy'),
    ('Japan Digital University (JDU)', 'xalqaro'),
    ('Kokand University', 'xususiy'),
    ("Latviyaning Axborot tizimlari menejmenti oliy maktabi Farg'ona filiali", 'xalqaro'),
    ('Mamun universiteti', 'xususiy'),
    ('Mehnat va ijtimoiy munosabatlar akademiyasi', 'xususiy'),
    ('Navoiy innovatsiyalar instituti', 'xususiy'),
    ('Nukus innovatsion instituti', 'xususiy'),
    ('Oriental University', 'xususiy'),
    ('Osiyo xalqaro universiteti', 'xalqaro'),
    ('PDP University', 'xususiy'),
    ('Perfect University', 'xususiy'),
    ('Profi University', 'xususiy'),
    ("Qarshi innovatsion ta'lim universiteti", 'xususiy'),
    ('Qarshi xalqaro universiteti', 'xalqaro'),
    ('Ranch texnologiya universiteti', 'xususiy'),
    ('Raqamli iqtisodiyot va agrotexnologiyalar universiteti', 'xususiy'),
    ("Renessans ta'lim universiteti", 'xususiy'),
    ('Sabhram University', 'xususiy'),
    ('Samarqand xalqaro texnologiya universiteti', 'xalqaro'),
    ('Sharda universiteti', 'xalqaro'),
    ('Stars International University', 'xususiy'),
    ('Tashkent International University of Education (TIUE)', 'xalqaro'),
    ('TEAM University', 'xususiy'),
    ('Termiz iqtisodiyot va servis universiteti', 'xususiy'),
    ('TMC Institute', 'xususiy'),
    ('Toshkent Amaliy fanlar universiteti', 'xususiy'),
    ('Toshkent Iqtisodiyot va pedagogika instituti', 'xususiy'),
    ('Toshkent menejment va iqtisodiyot universiteti', 'xususiy'),
    ('Toshkent shahrida Vebster universiteti', 'xalqaro'),
    ('Toshkent shahridagi Amiti universiteti', 'xalqaro'),
    ('Toshkent shahridagi Inha universiteti', 'xalqaro'),
    ('Toshkent shahridagi Puchon universiteti', 'xalqaro'),
    ('Toshkent shahridagi Turin politexnika universiteti', 'xalqaro'),
    ('Toshkent shahridagi Yeoju texnika instituti (KIUT)', 'xalqaro'),
    ('Toshkent shahridagi ADJU universiteti', 'xalqaro'),
    ('Toshkent xalqaro moliyaviy boshqaruv va texnologiyalar universiteti', 'xususiy'),
    ('Toshkentdagi Singapur menejmentni rivojlantirish instituti (MDIST)', 'xalqaro'),
    ('Turan International University', 'xalqaro'),
    ('Turkiya iqtisodiyot va texnologiyalar universitetining Toshkent filiali (TOBB)', 'xalqaro'),
    ('Turon Zarmed universiteti', 'xususiy'),
    ('University of Business and Science (UBS)', 'xususiy'),
    ('University of Economics and Pedagogy', 'xususiy'),
    ('University of Management and Future Technologies', 'xususiy'),
    ('Urganch innovatsion universiteti', 'xususiy'),
    ('Valley Innovative University', 'xususiy'),
    ('Xalqaro innovatsion universiteti', 'xalqaro'),
    ('Xalqaro Nordik universiteti', 'xalqaro'),
    ('Yangi asr universiteti', 'xususiy'),
]


# ── Journals grouped by OAK specialty code ──────────────────────────────────
JOURNALS_BY_SPECIALTY = {
    '01.00.00': [
        "BUXORO DAVLAT UNIVERSITETI ILMIY AXBOROTI", "MEXANIKA MUAMMOLARI",
        "O'ZMU XABARLARI", "NAMDU ILMIY AXBOROTNOMASI", "FARDU ILMIY XABARLAR",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "ILM SARCHASHMALARI",
        "QARDU XABARLARI", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "SAMDU ILMIY AXBOROTNOMASI",
    ],
    '02.00.00': [
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI",
        "FAN VA TEXNOLOGIYALAR TARAQQIYOTI", "SANOATDA RAQAMLI TEXNOLOGIYALAR",
        "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI", "O'ZMU XABARLARI",
        "NAMDU ILMIY AXBOROTNOMASI", "FARDU ILMIY XABARLAR",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "MILLIY STANDART",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "NAMANGAN MUHANDISLIK-TEXNOLOGIYA INSTITUTI ILMIY-TEXNIKA JURNALI",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "SAMDU ILMIY AXBOROTNOMASI",
    ],
    '03.00.00': [
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI", "O'ZBEKISTON ZAMINI",
        "O'ZMU XABARLARI", "NAMDU ILMIY AXBOROTNOMASI",
        "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI", "FARDU ILMIY XABARLAR",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "QARDU XABARLARI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "NAMANGAN MUHANDISLIK-TEXNOLOGIYA INSTITUTI ILMIY-TEXNIKA JURNALI",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "INFEKSIYA, IMMUNITET VA FARMAKOLOGIYA", "TUPROQSHUNOSLIK VA AGROKIMYO",
        "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "O'ZBEKISTON AGRAR FANI XABARNOMASI",
    ],
    '04.00.00': [
        "SANOATDA RAQAMLI TEXNOLOGIYALAR", "O'ZMU XABARLARI", "EKOLOGIYA XABARNOMASI",
        "FARDU ILMIY XABARLAR", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
    ],
    '05.00.00': [
        "MEXANIKA VA TEXNOLOGIYA", "QURILISH VA TA'LIM", "O'ZBEKISTON ZAMINI",
        "FAN VA TEXNOLOGIYALAR TARAQQIYOTI", "MEXANIKA MUAMMOLARI",
        "SANOATDA RAQAMLI TEXNOLOGIYALAR", "AL-FARG'ONIY AVLODLARI",
        "O'ZBEKISTON AGRAR FANI XABARNOMASI",
        "TRANSPORT VA TEXNOLOGIK MASHINALAR XALQARO JURNALI",
        "TRANSPORT VOSITALARI VA YO'LLARI ILMIY JURNALI",
        "TEMIR YO'L TRANSPORTI: DOLZARB MASALALAR VA INNOVATSIYALAR",
        "TA'LIM, FAN VA INNOVATSIYA", "MANAGEMENT AND FUTURE TECHNOLOGIES",
        "FAN VA INNOVATSION RIVOJLANISH", "MASHINASOZLIK", "TRANSPORT XABARNOMASI",
        "MUHANDISLIK VA IQTISODIYOT", "RAQAMLI TRANSFORMATSIYA VA SUN'IY INTELLEKT",
        "AGRO ILM", "RAQAMLI TEXNOLOGIYALARNING NAZARIY VA AMALIY MASALALARI",
        "MILLIY STANDART", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "NAMANGAN MUHANDISLIK-TEXNOLOGIYA INSTITUTI ILMIY-TEXNIKA JURNALI",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "INNOVATION SCIENCE AND TECHNOLOGY", "INNOVATIONS IN SCIENCE AND TECHNOLOGIES",
        "TEXNIKA FANLARINING DOLZARB MUAMMOLARI", "AGROMUHANDISLIK YECHIMLARI",
        "INNORES", "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI",
    ],
    '06.00.00': [
        "O'ZBEKISTON ZAMINI", "SCIENCE AND EDUCATION IN AGRICULTURE",
        "SUSTAINABLE AGRICULTURE", "O'ZMU XABARLARI", "EKOLOGIYA XABARNOMASI",
        "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI", "AGRO ILM",
        "O'ZBEKISTON QISHLOQ VA SUV XO'JALIGI",
        "AGRO KIMYO-HIMOYA VA O'SIMLIKLAR KARANTINI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "CHORVACHILIK VA NASLCHILIK ISHI",
        "AGROINNOVATSIYA", "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "TUPROQSHUNOSLIK VA AGROKIMYO", "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "O'ZBEKISTON AGRAR FANI XABARNOMASI",
    ],
    '07.00.00': [
        "FAN VA TA'LIM INTEGRATSIYASI", "TA'LIM TIZIMIDA IJTIMOIY GUMANITAR FANLAR",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI", "O'ZMU XABARLARI",
        "LINGVOSPEKTR", "FALSAFIY TADQIQOTLAR VA IJTIMOIY FANLAR",
        "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI", "JAMIYAT VA INNOVATSIYALAR",
        "FARDU ILMIY XABARLAR", "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "TAMADDUN NURI",
        "QARDU XABARLARI", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "SHARQ TARIXI, SIYOSATI VA HUQUQI JURNALI", "SHARQ IJTIMOIY FANLAR JURNALI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)", "SAMDU ILMIY AXBOROTNOMASI",
        "TA'LIM VA INNOVATSION TADQIQOTLAR", "MOTURIDIYLIK",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR",
    ],
    '08.00.00': [
        "TA'LIM TIZIMIDA IJTIMOIY GUMANITAR FANLAR", "IQTISODIYOT: TAHLILLAR VA PROGNOZLAR",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "O'ZBEKISTON STATISTIKA AXBOROTNOMASI", "AGROBIZNES, FAN VA TEXNOLOGIYALAR",
        "INSON KAPITALI VA IJTIMOIY RIVOJLANISH", "O'ZBEKISTON ZAMINI",
        "SCIENCE AND EDUCATION IN AGRICULTURE", "IQTISODIY TARAQQIYOT VA TAHLIL",
        "DEVELOPMENT OF SCIENCE", "TA'LIM, FAN VA INNOVATSIYA", "TRANSPORT XABARNOMASI",
        "YASHIL IQTISODIYOT VA TA'LIM", "MUHANDISLIK VA IQTISODIYOT",
        "RAQAMLI TRANSFORMATSIYA VA SUN'IY INTELLEKT",
        "MEHNAT IQTISODIYOTI VA INSON KAPITALI", "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI",
        "AGRO ILM", "O'ZBEKISTON QISHLOQ VA SUV XO'JALIGI", "FARDU ILMIY XABARLAR",
        "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "RAQAMLI IQTISODIYOT", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "O'ZBEKISTON SUG'URTA BOZORI", "IQTISODIYOT VA INNOVATSION TEXNOLOGIYALAR",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "NAMANGAN MUHANDISLIK-TEXNOLOGIYA INSTITUTI ILMIY-TEXNIKA JURNALI",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)", "INNOVATIONS IN SCIENCE AND TECHNOLOGIES",
        "INNOVATION SCIENCE AND TECHNOLOGY", "INNOVATSION IQTISODIYOT", "NORDIC",
        "TISU ILMIY TADQIQOTLAR XABARNOMASI",
        "ILG'OR IQTISODIYOT VA PEDAGOGIK TEXNOLOGIYALAR",
    ],
    '09.00.00': [
        "TA'LIM TIZIMIDA IJTIMOIY GUMANITAR FANLAR",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE", "O'ZMU XABARLARI",
        "FALSAFIY TADQIQOTLAR VA IJTIMOIY FANLAR", "FALSAFA VA HUQUQ",
        "NAMDU ILMIY AXBOROTNOMASI", "FARDU ILMIY XABARLAR",
        "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "TAMADDUN NURI",
        "ILM SARCHASHMALARI", "QARDU XABARLARI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "SHARQ TARIXI, SIYOSATI VA HUQUQI JURNALI", "SHARQ IJTIMOIY FANLAR JURNALI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)",
        "SAMDU ILMIY AXBOROTNOMASI",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR",
    ],
    '10.00.00': [
        "BUXORO DAVLAT UNIVERSITETI ILMIY AXBOROTI", "TIL, TA'LIM, TARJIMA",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI",
        "MARKAZIY OSIYODA MEDIA VA OMMAVIY KOMMUNIKATSIYALAR", "O'ZMU XABARLARI",
        "LINGVOSPEKTR", "TIL VA ADABIYOT TA'LIMI", "FILOLOGIYA MASALALARI",
        "NAMDU ILMIY AXBOROTNOMASI", "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI",
        "XORIJIY LINGVISTIKA VA LINGVODIDAKTIKA", "FARDU ILMIY XABARLAR",
        "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "O'ZBEKISTONDA XORIJIY TILLAR",
        "TAMADDUN NURI", "ILM SARCHASHMALARI", "QARDU XABARLARI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "O'ZBEKISTON: TIL VA MADANIYAT", "OLTIN BITIGLAR",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)", "SAMDU ILMIY AXBOROTNOMASI",
        "KOMPARATIVISTIKA", "FILOLOGIYA VA PEDAGOGIKA", "SHARQ FILOLOGIYASI",
        "TA'LIM VA INNOVATSION TADQIQOTLAR",
        "O'ZBEKISTON OLIMLARINING ILMIY-AMALIY TADQIQOTLARI",
        "FILOLOGIK TADQIQOTLAR: TIL, ADABIYOT, TA'LIM",
        "BUXORO XALQARO UNIVERSITETI ILMIY AXBOROTNOMASI",
        "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR", "ILM VAQTI",
    ],
    '11.00.00': [
        "O'ZBEKISTON ZAMINI", "O'ZMU XABARLARI", "EKOLOGIYA XABARNOMASI",
        "O'ZBEKISTON OLIMLARINING ILMIY-AMALIY TADQIQOTLARI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "SAMDU ILMIY AXBOROTNOMASI",
    ],
    '12.00.00': [
        "YURIST AXBOROTNOMASI", "FALSAFA VA HUQUQ", "JAMIYAT VA INNOVATSIYALAR",
        "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI", "TAMADDUN NURI",
        "SHARQ TARIXI, SIYOSATI VA HUQUQI JURNALI", "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)",
    ],
    '13.00.00': [
        "PEDAGOGIK MAHORAT", "FAN VA TA'LIM INTEGRATSIYASI", "SAYHUN ILMIY AXBOROTNOMASI",
        "TA'LIM VA TARAQQIYOT", "TADBIRKORLIK VA PEDAGOGIKA",
        "TA'LIM TIZIMIDA IJTIMOIY GUMANITAR FANLAR",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI",
        "MAKTABGACHA VA MAKTAB TA'LIMI", "BELARUS-O'ZBEK ILMIY-METODIK JURNAL",
        "TA'LIMDA ISTIQBOLLI IZLANISHLAR", "ADPI ILMIY XABARNOMASI",
        "DEVELOPMENT OF SCIENCE", "TA'LIM, FAN VA INNOVATSIYA", "O'ZMU XABARLARI",
        "LINGVOSPEKTR", "TIL VA ADABIYOT TA'LIMI", "FILOLOGIYA MASALALARI",
        "INTER EDUCATION & GLOBAL STUDY", "NAMDU ILMIY AXBOROTNOMASI",
        "URGANCH DAVLAT PEDAGOGIKA INSTITUTI AXBOROTNOMASI", "JAMIYAT VA INNOVATSIYALAR",
        "XORIJIY LINGVISTIKA VA LINGVODIDAKTIKA", "FARDU ILMIY XABARLAR",
        "IJTIMOIY-GUMANITAR FANLARNING DOLZARB MUAMMOLARI",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "O'ZBEKISTONDA XORIJIY TILLAR",
        "TAMADDUN NURI", "ILM SARCHASHMALARI", "QARDU XABARLARI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "BADIIY TA'LIM VA PEDAGOGIKA", "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "FAN VA JAMIYAT", "SAMDU ILMIY AXBOROTNOMASI", "FARG'ONA METODIK JURNALI",
        "FILOLOGIYA VA PEDAGOGIKA", "SHARQ TA'LIMI", "KASB-HUNAR TA'LIMI",
        "TA'LIM VA INNOVATSION TADQIQOTLAR", "NORDIC",
        "BUXORO XALQARO UNIVERSITETI ILMIY AXBOROTNOMASI", "UBS ILMIY AXBOROTNOMASI",
        "OSIYO XALQARO UNIVERSITETI AXBOROTNOMASI",
        "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI", "SCIENCE AND EDUCATION NEWS",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR", "ILM VAQTI",
        "ILG'OR IQTISODIYOT VA PEDAGOGIK TEXNOLOGIYALAR",
    ],
    '14.00.00': [
        "O'ZBEKISTON TIBBIYOT JURNALI", "INTERNATIONAL JOURNAL OF SCIENTIFIC PEDIATRICS",
        "MEDICAL SCIENCE OF UZBEKISTAN", "GUMANITAR VA TABIIY FANLAR JURNALI",
        "MARKAZIY OSIYO PULMONOLOGLAR ASSOTSIATSIYASI AXBOROTNOMA",
        "CENTRAL ASIAN JOURNAL OF MEDICINE", "DOKTOR AXBOROTNOMASI", "TIBBIYOTDA YANGI KUN",
        "STOMATOLOGIYA", "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "O'Z.A ILM-FAN BO'LIMI (ELEKTRON JURNAL)",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "INFEKSIYA, IMMUNITET VA FARMAKOLOGIYA", "BIOLOGIYA VA TIBBIYOT MUAMMOLARI",
        "SHOSHILINCH TIBBIYOT AXBOROTNOMASI", "PROFILAKTIK TIBBIYOT VA SALOMATLIK",
        "INTEGRATIV STOMATOLOGIYA VA YUZ-JAG' JARROHLIGI",
        "EUROASIAN JOURNAL OF OTORHINOLARYNGOLOGY-HEAD AND NECK SURGERY",
        "TIBBIYOT ASOSLARI", "ZAMONAVIY TIBBIYOT JURNALI",
    ],
    '15.00.00': [
        "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "INFEKSIYA, IMMUNITET VA FARMAKOLOGIYA",
    ],
    '16.00.00': [
        "EKOLOGIYA XABARNOMASI", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "CHORVACHILIK VA NASLCHILIK ISHI",
        "RESEARCH FOCUS",
    ],
    '17.00.00': [
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI",
        "INTER EDUCATION & GLOBAL STUDY", "ORIENTAL ART AND CULTURE",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "BADIIY TA'LIM VA PEDAGOGIKA", "QORAQALPOG'ISTONDA FAN VA TA'LIM",
        "SAN'AT VA MADANIYAT AXBOROTNOMASI", "MILLIY MADANIYAT",
    ],
    '18.00.00': [
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE", "O'ZBEKISTON ZAMINI",
        "XORAZM MA'MUN AKADEMIYASI AXBOROTNOMASI", "ARXITEKTURA, QURILISH VA DIZAYN",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM",
    ],
    '19.00.00': [
        "PEDAGOGIK MAHORAT", "PSIXOLOGIYA", "FAN VA TA'LIM INTEGRATSIYASI",
        "TA'LIM TIZIMIDA IJTIMOIY GUMANITAR FANLAR",
        "QO'QON DAVLAT PEDAGOGIKA INSTITUTI ILMIY XABARLARI",
        "TA'LIMDA ISTIQBOLLI IZLANISHLAR", "TA'LIM, FAN VA INNOVATSIYA", "O'ZMU XABARLARI",
        "INTER EDUCATION & GLOBAL STUDY", "URGANCH DAVLAT PEDAGOGIKA INSTITUTI AXBOROTNOMASI",
        "O'ZBEKISTON OLIMLARINING ILMIY-AMALIY TADQIQOTLARI", "FARDU ILMIY XABARLAR",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI", "TAMADDUN NURI",
        "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "FAN VA JAMIYAT", "SAMDU ILMIY AXBOROTNOMASI",
        "MAKTABGACHA VA MAKTAB TA'LIMI", "TA'LIM VA INNOVATSION TADQIQOTLAR",
        "BUXORO XALQARO UNIVERSITETI ILMIY AXBOROTNOMASI", "UBS ILMIY AXBOROTNOMASI",
        "OSIYO XALQARO UNIVERSITETI AXBOROTNOMASI",
        "GULISTON DAVLAT UNIVERSITETI AXBOROTNOMASI", "SCIENCE AND EDUCATION NEWS",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR",
    ],
    '22.00.00': [
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE", "O'ZMU XABARLARI",
        "FALSAFA VA HUQUQ", "ZAMONAVIY FAN, TA'LIM VA TARBIYANING DOLZARB MUAMMOLARI",
        "QORAQALPOG'ISTONDA FAN VA TA'LIM", "SAMDU ILMIY AXBOROTNOMASI",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR",
    ],
    '23.00.00': [
        "BUXORO DAVLAT UNIVERSITETI ILMIY AXBOROTI",
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE",
        "TA'LIM, FAN VA INNOVATSIYA", "O'ZMU XABARLARI", "FALSAFA VA HUQUQ",
        "JAMIYAT VA INNOVATSIYALAR",
        "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA", "QARDU XABARLARI",
        "SHARQ TARIXI, SIYOSATI VA HUQUQI JURNALI", "SHARQ IJTIMOIY FANLAR JURNALI",
        "O'ZBEKISTON RESPUBLIKASI FANLAR AKADEMIYASI MA'RUZALARI",
        "SAMDU ILMIY AXBOROTNOMASI", "UBS ILMIY AXBOROTNOMASI",
        "IJTIMOIY-GUMANITAR SOHADA ILMIY-INNOVATSION TADQIQOTLAR",
    ],
    '24.00.00': [
        "INTERNATIONAL JOURNAL OF INTELLECTUAL AND CULTURAL HERITAGE", "O'ZMU XABARLARI",
        "FALSAFA VA HUQUQ", "BERDAQ NOMIDAGI QORAQALPOQ DAVLAT UNIVERSITETI AXBOROTNOMASI",
        "ANDIJON DAVLAT UNIVERSITETI ILMIY XABARNOMA",
        "SHARQ TARIXI, SIYOSATI VA HUQUQI JURNALI", "SAMDU ILMIY AXBOROTNOMASI",
        "MOTURIDIYLIK",
    ],
}
