#!/usr/bin/env bash
#
# One-shot, idempotent production deploy for Olimlar.uz on a Google Compute
# Engine VM (Ubuntu). Installs system packages, sets up a venv, writes the
# systemd + nginx config, and (if DNS already points here) obtains a Let's
# Encrypt certificate. Safe to re-run.
#
# Usage (run ON the VM, as a sudo-capable user):
#   DATABASE_URL='postgresql://USER:PASS@host/db?sslmode=require' \
#   SESSION_SECRET='<64-hex or leave unset to auto-generate>' \
#   DOMAIN='olimlar.uz' CERTBOT_EMAIL='admin@olimlar.uz' \
#   sudo -E bash deploy/deploy.sh
#
set -euo pipefail

# ── Config (override via env) ───────────────────────────────────────────────
REPO_URL="${REPO_URL:-https://github.com/botirbekbahodirovich-gif/oak-dissertatsiya.git}"
APP_DIR="${APP_DIR:-/opt/olimlar-uz}"
DOMAIN="${DOMAIN:-olimlar.uz}"
SERVER_IP="${SERVER_IP:-34.141.70.133}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-admin@${DOMAIN}}"
BIND="127.0.0.1:8000"
SERVICE="olimlar"
DEPLOY_USER="${SUDO_USER:-$(id -un)}"

log() { echo -e "\n\033[1;36m== $* ==\033[0m"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo -E bash deploy/deploy.sh" >&2; exit 1
fi
if [ -z "${DATABASE_URL:-}" ]; then
  echo "ERROR: DATABASE_URL env var is required (passed via sudo -E)." >&2; exit 1
fi

# ── 1. System packages ──────────────────────────────────────────────────────
log "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  python3 python3-venv python3-dev python3-pip \
  git nginx certbot python3-certbot-nginx \
  libpq-dev build-essential curl ca-certificates

# Prefer a 3.11+ interpreter; fall back to system python3 (>=3.10 works fine).
PYBIN="$(command -v python3.12 || command -v python3.11 || command -v python3)"
echo "Using interpreter: $PYBIN ($($PYBIN --version))"

# ── 2. Code ─────────────────────────────────────────────────────────────────
log "Fetching code into $APP_DIR"
mkdir -p "$APP_DIR"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --depth 1 origin main
  git -C "$APP_DIR" reset --hard origin/main
else
  git clone --depth 1 "$REPO_URL" "$APP_DIR"
fi
chown -R "$DEPLOY_USER":"$DEPLOY_USER" "$APP_DIR"

# ── 3. venv + dependencies ──────────────────────────────────────────────────
log "Creating venv and installing requirements"
sudo -u "$DEPLOY_USER" "$PYBIN" -m venv "$APP_DIR/venv"
sudo -u "$DEPLOY_USER" "$APP_DIR/venv/bin/pip" install --upgrade pip
sudo -u "$DEPLOY_USER" "$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt"
sudo -u "$DEPLOY_USER" "$APP_DIR/venv/bin/pip" install gunicorn

# ── 4. .env (secrets stay on the VM, never in git) ──────────────────────────
log "Writing $APP_DIR/.env"
SESSION_SECRET="${SESSION_SECRET:-$(python3 -c 'import secrets;print(secrets.token_hex(32))')}"
umask 077
cat > "$APP_DIR/.env" <<ENV
# Generated by deploy.sh — do not commit
SESSION_SECRET=${SESSION_SECRET}
DATABASE_URL=${DATABASE_URL}
ENV
# Carry over optional keys if provided in the environment.
for k in GROQ_API_KEY GEMINI_API_KEY OAK_API_KEY GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET \
         GOOGLE_REDIRECT_URI TELEGRAM_BOT_TOKEN TELEGRAM_BOT_USERNAME SITE_API_URL SITE_API_KEY; do
  v="${!k:-}"; [ -n "$v" ] && echo "$k=$v" >> "$APP_DIR/.env"
done
chown "$DEPLOY_USER":"$DEPLOY_USER" "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"

# ── 5a. systemd service (Gunicorn) ──────────────────────────────────────────
log "Installing systemd service: $SERVICE"
cat > "/etc/systemd/system/${SERVICE}.service" <<UNIT
[Unit]
Description=Olimlar.uz Gunicorn (Flask)
After=network.target

[Service]
User=${DEPLOY_USER}
Group=${DEPLOY_USER}
WorkingDirectory=${APP_DIR}
ExecStart=${APP_DIR}/venv/bin/gunicorn app:app --bind ${BIND} --workers 2 --threads 2 --timeout 120
Restart=always
RestartSec=3
KillMode=mixed

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable "$SERVICE"
systemctl restart "$SERVICE"

# ── 5b. Nginx reverse proxy ────────────────────────────────────────────────
log "Configuring nginx for $DOMAIN"
cat > "/etc/nginx/sites-available/${DOMAIN}" <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    client_max_body_size 250M;

    location /static/ {
        alias ${APP_DIR}/static/;
        expires 7d;
        access_log off;
    }

    location / {
        proxy_pass http://${BIND};
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 120s;
        proxy_send_timeout    120s;
        proxy_read_timeout    120s;
    }
}
NGINX
ln -sf "/etc/nginx/sites-available/${DOMAIN}" "/etc/nginx/sites-enabled/${DOMAIN}"
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ── 5c. SSL via certbot (only if DNS already resolves to this VM) ───────────
log "Checking DNS for TLS"
RESOLVED="$(getent hosts "$DOMAIN" | awk '{print $1}' | head -1 || true)"
if [ "$RESOLVED" = "$SERVER_IP" ]; then
  echo "DNS OK ($DOMAIN -> $SERVER_IP). Requesting certificate..."
  certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" \
    --non-interactive --agree-tos -m "$CERTBOT_EMAIL" --redirect || \
    echo "certbot failed — re-run after DNS fully propagates: certbot --nginx -d $DOMAIN -d www.$DOMAIN"
else
  echo "SKIP TLS: $DOMAIN currently resolves to '${RESOLVED:-nothing}', not $SERVER_IP."
  echo "Point the A record to $SERVER_IP, then run:"
  echo "  sudo certbot --nginx -d $DOMAIN -d www.$DOMAIN --agree-tos -m $CERTBOT_EMAIL --redirect"
fi

# ── 6. Smoke test ───────────────────────────────────────────────────────────
log "Smoke test"
sleep 2
systemctl --no-pager --full status "$SERVICE" | head -8 || true
for p in /login /journals /universities /; do
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 60 "http://${BIND}${p}" || echo 000)
  echo "  $code  http://${BIND}${p}"
done

log "DONE"
echo "App dir : $APP_DIR  (user: $DEPLOY_USER)"
echo "Service : systemctl status $SERVICE   |   logs: journalctl -u $SERVICE -f"
echo "Site    : http://$DOMAIN  (https after certbot)"
